"use client";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Session } from "@/lib/types";

export function ParentModal({ onClose }: { onClose: () => void }) {
  const [summary, setSummary] = useState<string>("");
  const [sessions, setSessions] = useState<Session[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/parent-summary")
      .then((r) => r.json())
      .then((d) => {
        setSummary(d.summary);
        setSessions(d.sessions);
      })
      .finally(() => setLoading(false));
  }, []);

  const totalCorrect = sessions.filter((s) => s.correct).length;
  const accuracy = sessions.length ? Math.round((totalCorrect / sessions.length) * 100) : 0;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-2"
    >
      <motion.div
        initial={{ y: 40, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        className="w-full max-w-md bg-white rounded-3xl p-5 shadow-2xl max-h-[90vh] overflow-y-auto"
      >
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-lg font-bold">👨‍👩‍👧 For Parents</h2>
          <button onClick={onClose} className="text-2xl px-2 text-gray-500">
            ✕
          </button>
        </div>

        <div className="grid grid-cols-3 gap-2 mb-4">
          <Stat label="Problems" value={sessions.length} />
          <Stat label="Accuracy" value={`${accuracy}%`} />
          <Stat label="Sessions" value={1} />
        </div>

        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 min-h-[180px] whitespace-pre-wrap text-sm text-gray-700 leading-relaxed">
          {loading ? (
            <div className="flex items-center gap-2 text-gray-500">
              <span className="animate-pulse">Sparky is writing your report…</span>
            </div>
          ) : (
            renderMarkdown(summary)
          )}
        </div>

        <div className="text-xs text-gray-400 mt-3 text-center">
          Generated by Claude on live session telemetry.
        </div>
      </motion.div>
    </motion.div>
  );
}

function Stat({ label, value }: { label: string; value: number | string }) {
  return (
    <div className="bg-sky-50 border border-sky-100 rounded-xl py-2 text-center">
      <div className="text-lg font-bold text-sky-700">{value}</div>
      <div className="text-[10px] uppercase tracking-wide text-gray-500 font-semibold">{label}</div>
    </div>
  );
}

// Minimal markdown renderer: bold + paragraphs
function renderMarkdown(md: string) {
  return md.split(/\n\n+/).map((para, i) => (
    <p key={i} className="mb-2 last:mb-0">
      {para.split(/(\*\*[^*]+\*\*)/g).map((chunk, j) =>
        chunk.startsWith("**") && chunk.endsWith("**") ? (
          <strong key={j}>{chunk.slice(2, -2)}</strong>
        ) : (
          <span key={j}>{chunk}</span>
        )
      )}
    </p>
  ));
}
